Grd 407
oicr-gsi/cramConverter pull request #1
Opened 2022-03-04 18:46 UTC by xuemeiluo

2022-03-07 15:31 UTC, pruzanov requested changes

2022-03-07 15:31 UTC, pruzanov commented on commands.txt
> +=== Description here ===.
THis is a placeholder, may need to add the actual description here

2022-03-07 15:31 UTC, pruzanov commented on cram.wdl
> +        File? outputBam = cramToBam.outputBam
I am not sure if it is Ok to have all outputs optional, perhaps we can output a log file that is not optional here?

2022-03-07 15:31 UTC, pruzanov commented on cram.wdl
> +    File? inputBam
Why this is optional?

2022-03-07 15:31 UTC, pruzanov commented on cram.wdl
> +    File? inputCram
Why this is optional?

2022-03-07 15:31 UTC, pruzanov commented on cram.wdl
> +        File? outputBam = cramToBam.outputBam
File convertionLog = select_first([bamToCram.log, cramToBam.log])

2022-03-21 15:40 UTC, pruzanov approved these changes

2022-03-22 13:46 UTC, lheisler commented
lets change the name of this from
cram -> cramConverter

2022-03-23 21:07 UTC, mlaszloffy approved these changes

2022-03-24 13:58 UTC, merged